-- Created by Vertabelo (http://vertabelo.com)
-- Last modification date: 2016-06-15 01:46:19.775
CREATE DATABASE BD_FARMACIA
GO
USE BD_FARMACIA
GO
-- tables
-- Table: ADVERTENCIA
CREATE TABLE ADVERTENCIA (
    ID_ADV int  NOT NULL IDENTITY(1,1),
    DES_ADV nvarchar(200)  NOT NULL,
    CONSTRAINT ADVERTENCIA_pk PRIMARY KEY  (ID_ADV)
);

-- Table: DEPARTAMENTO
CREATE TABLE DEPARTAMENTO (
    ID_DEP int  NOT NULL IDENTITY(1,1),
    DES_DEP nvarchar(100)  NOT NULL,
    CONSTRAINT DEPARTAMENTO_pk PRIMARY KEY  (ID_DEP)
);

-- Table: DISTRITO
CREATE TABLE DISTRITO (
    ID_DIS int  NOT NULL IDENTITY(1,1),
    ID_PRO int  NOT NULL,
    DES_DIS nvarchar(100)  NOT NULL,
    CONSTRAINT DISTRITO_pk PRIMARY KEY  (ID_DIS)
);

-- Table: FARMACIA
CREATE TABLE FARMACIA (
    ID_FAR int  NOT NULL IDENTITY(1,1),
    ID_DIS int  NOT NULL,
    NOM_FAR nvarchar(100)  NOT NULL,
    DIR_FAR nvarchar(300)  NULL,
    CORX_FAR real  NULL,
    CORDY_FAR real  NULL,
    HORARIO_FAR int  NULL,
    GEO_LUGAR geography  NULL,
    CONSTRAINT FARMACIA_pk PRIMARY KEY  (ID_FAR)
);

-- Table: FAVORITO
CREATE TABLE FAVORITO (
    ID_FAV int  NOT NULL IDENTITY(1,1),
    ID_MED int  NOT NULL,
    ID_USU int  NOT NULL,
    CONSTRAINT FAVORITO_pk PRIMARY KEY  (ID_FAV)
);

-- Table: FORMA_USO
CREATE TABLE FORMA_USO (
    ID_FOR int  NOT NULL IDENTITY(1,1),
    DES_FOR nvarchar(300)  NOT NULL,
    CONSTRAINT FORMA_USO_pk PRIMARY KEY  (ID_FOR)
);

-- Table: LABORATORIO
CREATE TABLE LABORATORIO (
    ID_LAB int  NOT NULL IDENTITY(1,1),
    NOM_LAB nvarchar(300)  NOT NULL,
    RSO_LAB nvarchar(300)  NULL,
    CONSTRAINT LABORATORIO_pk PRIMARY KEY  (ID_LAB)
);

-- Table: LABORATORIO_MEDICAMENTO
CREATE TABLE LABORATORIO_MEDICAMENTO (
    ID_LABMED int  NOT NULL IDENTITY(1,1),
    ID_LAB int  NOT NULL,
    ID_MED int  NOT NULL,
    CONSTRAINT LABORATORIO_MEDICAMENTO_pk PRIMARY KEY  (ID_LABMED)
);

-- Table: MEDICAMENTO
CREATE TABLE MEDICAMENTO (
    ID_MED int  NOT NULL IDENTITY(1,1),
    ID_ADV int  NOT NULL,
    ID_FOR int  NOT NULL,
    NOM_MED nvarchar(200)  NOT NULL,
    CONSTRAINT MEDICAMENTO_pk PRIMARY KEY  (ID_MED)
);

-- Table: MEDICAMENTO_FARMACIA
CREATE TABLE MEDICAMENTO_FARMACIA (
    ID_MEDFAR int  NOT NULL IDENTITY(1,1),
    ID_MED int  NOT NULL,
    ID_FAR int  NOT NULL,
    PRECIO money  NOT NULL,
    CONSTRAINT MEDICAMENTO_FARMACIA_pk PRIMARY KEY  (ID_MEDFAR)
);

-- Table: MEDICAMENTO_SINTOMA
CREATE TABLE MEDICAMENTO_SINTOMA (
    ID_MEDSIN int  NOT NULL IDENTITY(1,1),
    ID_SIN int  NOT NULL,
    ID_MED int  NOT NULL,
    CONSTRAINT MEDICAMENTO_SINTOMA_pk PRIMARY KEY  (ID_MEDSIN)
);

-- Table: PERSONA
CREATE TABLE PERSONA (
    PER_ID int  NOT NULL IDENTITY(1,1),
    ID_USU int  NOT NULL,
    NOM_PER nvarchar(60)  NOT NULL,
    APEP_PER nvarchar(60)  NOT NULL,
    APEM_PER nvarchar(60)  NOT NULL,
    FNAC_PER datetime  NULL,
    CONSTRAINT PERSONA_pk PRIMARY KEY  (PER_ID)
);

-- Table: PROMOCION
CREATE TABLE PROMOCION (
    ID_PRO int  NOT NULL IDENTITY(1,1),
    ID_MED int  NOT NULL,
    ID_FAR int  NOT NULL,
    DES_PRO nvarchar(300)  NOT NULL,
    CONSTRAINT PROMOCION_pk PRIMARY KEY  (ID_PRO,ID_MED,ID_FAR)
);

-- Table: PROVINCIA
CREATE TABLE PROVINCIA (
    ID_PRO int  NOT NULL IDENTITY(1,1),
    ID_DEP int  NOT NULL,
    DES_PRO nvarchar(100)  NOT NULL,
    CONSTRAINT PROVINCIA_pk PRIMARY KEY  (ID_PRO)
);

-- Table: SINTOMA
CREATE TABLE SINTOMA (
    ID_SIN int  NOT NULL IDENTITY(1,1),
    DES_SIN nvarchar(100)  NOT NULL,
    CONSTRAINT SINTOMA_pk PRIMARY KEY  (ID_SIN)
);

-- Table: USUARIO
CREATE TABLE USUARIO (
    ID_USU int  NOT NULL IDENTITY(1,1),
    NOM_USU nvarchar(30)  NOT NULL,
    PASS_USU nvarchar(30)  NOT NULL,
    CORREO_USU nvarchar(150)  NULL,
    CONSTRAINT USUARIO_pk PRIMARY KEY  (ID_USU)
);

-- foreign keys
-- Reference: DISTRITO_PROVINCIA (table: DISTRITO)
ALTER TABLE DISTRITO ADD CONSTRAINT DISTRITO_PROVINCIA
    FOREIGN KEY (ID_PRO)
    REFERENCES PROVINCIA (ID_PRO);

-- Reference: FARMACIA_DISTRITO (table: FARMACIA)
ALTER TABLE FARMACIA ADD CONSTRAINT FARMACIA_DISTRITO
    FOREIGN KEY (ID_DIS)
    REFERENCES DISTRITO (ID_DIS);

-- Reference: FAVORITO_MEDICAMENTO (table: FAVORITO)
ALTER TABLE FAVORITO ADD CONSTRAINT FAVORITO_MEDICAMENTO
    FOREIGN KEY (ID_MED)
    REFERENCES MEDICAMENTO (ID_MED);

-- Reference: FAVORITO_USUARIO (table: FAVORITO)
ALTER TABLE FAVORITO ADD CONSTRAINT FAVORITO_USUARIO
    FOREIGN KEY (ID_USU)
    REFERENCES USUARIO (ID_USU);

-- Reference: LABORATORIO_MEDICAMENTO_LABORATORIO (table: LABORATORIO_MEDICAMENTO)
ALTER TABLE LABORATORIO_MEDICAMENTO ADD CONSTRAINT LABORATORIO_MEDICAMENTO_LABORATORIO
    FOREIGN KEY (ID_LAB)
    REFERENCES LABORATORIO (ID_LAB);

-- Reference: LABORATORIO_MEDICAMENTO_MEDICAMENTO (table: LABORATORIO_MEDICAMENTO)
ALTER TABLE LABORATORIO_MEDICAMENTO ADD CONSTRAINT LABORATORIO_MEDICAMENTO_MEDICAMENTO
    FOREIGN KEY (ID_MED)
    REFERENCES MEDICAMENTO (ID_MED);

-- Reference: MEDICAMENTO_ADVERTENCIA (table: MEDICAMENTO)
ALTER TABLE MEDICAMENTO ADD CONSTRAINT MEDICAMENTO_ADVERTENCIA
    FOREIGN KEY (ID_ADV)
    REFERENCES ADVERTENCIA (ID_ADV);

-- Reference: MEDICAMENTO_FARMACIA_FARMACIA (table: MEDICAMENTO_FARMACIA)
ALTER TABLE MEDICAMENTO_FARMACIA ADD CONSTRAINT MEDICAMENTO_FARMACIA_FARMACIA
    FOREIGN KEY (ID_FAR)
    REFERENCES FARMACIA (ID_FAR);

-- Reference: MEDICAMENTO_FARMACIA_MEDICAMENTO (table: MEDICAMENTO_FARMACIA)
ALTER TABLE MEDICAMENTO_FARMACIA ADD CONSTRAINT MEDICAMENTO_FARMACIA_MEDICAMENTO
    FOREIGN KEY (ID_MED)
    REFERENCES MEDICAMENTO (ID_MED);

-- Reference: MEDICAMENTO_FORMA_USO (table: MEDICAMENTO)
ALTER TABLE MEDICAMENTO ADD CONSTRAINT MEDICAMENTO_FORMA_USO
    FOREIGN KEY (ID_FOR)
    REFERENCES FORMA_USO (ID_FOR);

-- Reference: MEDICAMENTO_SINTOMA_MEDICAMENTO (table: MEDICAMENTO_SINTOMA)
ALTER TABLE MEDICAMENTO_SINTOMA ADD CONSTRAINT MEDICAMENTO_SINTOMA_MEDICAMENTO
    FOREIGN KEY (ID_MED)
    REFERENCES MEDICAMENTO (ID_MED);

-- Reference: MEDICAMENTO_SINTOMA_SINTOMA (table: MEDICAMENTO_SINTOMA)
ALTER TABLE MEDICAMENTO_SINTOMA ADD CONSTRAINT MEDICAMENTO_SINTOMA_SINTOMA
    FOREIGN KEY (ID_SIN)
    REFERENCES SINTOMA (ID_SIN);

-- Reference: PERSONA_USUARIO (table: PERSONA)
ALTER TABLE PERSONA ADD CONSTRAINT PERSONA_USUARIO
    FOREIGN KEY (ID_USU)
    REFERENCES USUARIO (ID_USU);

-- Reference: PROMOCION_FARMACIA (table: PROMOCION)
ALTER TABLE PROMOCION ADD CONSTRAINT PROMOCION_FARMACIA
    FOREIGN KEY (ID_FAR)
    REFERENCES FARMACIA (ID_FAR);

-- Reference: PROMOCION_MEDICAMENTO (table: PROMOCION)
ALTER TABLE PROMOCION ADD CONSTRAINT PROMOCION_MEDICAMENTO
    FOREIGN KEY (ID_MED)
    REFERENCES MEDICAMENTO (ID_MED);

-- Reference: PROVINCIA_DEPARTAMENTO (table: PROVINCIA)
ALTER TABLE PROVINCIA ADD CONSTRAINT PROVINCIA_DEPARTAMENTO
    FOREIGN KEY (ID_DEP)
    REFERENCES DEPARTAMENTO (ID_DEP);

-- End of file.
GO

USE BD_FARMACIA
GO
-- DEPARTAMENTO
INSERT INTO DEPARTAMENTO (DES_DEP) VALUES ('LIMA')
GO
-- PROVINCIA
INSERT INTO PROVINCIA (ID_DEP,DES_PRO) VALUES (1,'LIMA')
GO
-- DISTRITO
INSERT INTO DISTRITO (ID_PRO,DES_DIS) VALUES (1,'ANCON')
INSERT INTO DISTRITO (ID_PRO,DES_DIS) VALUES (1,'ATE')
INSERT INTO DISTRITO (ID_PRO,DES_DIS) VALUES (1,'BARRANCO')
INSERT INTO DISTRITO (ID_PRO,DES_DIS) VALUES (1,'BREÑA')
INSERT INTO DISTRITO (ID_PRO,DES_DIS) VALUES (1,'CARABAYLLO')
INSERT INTO DISTRITO (ID_PRO,DES_DIS) VALUES (1,'CHACLACAYO')
INSERT INTO DISTRITO (ID_PRO,DES_DIS) VALUES (1,'CHORRILLOS')
INSERT INTO DISTRITO (ID_PRO,DES_DIS) VALUES (1,'CIENEGUILLA')
INSERT INTO DISTRITO (ID_PRO,DES_DIS) VALUES (1,'COMAS')
INSERT INTO DISTRITO (ID_PRO,DES_DIS) VALUES (1,'EL AGUSTINO')
INSERT INTO DISTRITO (ID_PRO,DES_DIS) VALUES (1,'INDEPENDENCIA')
INSERT INTO DISTRITO (ID_PRO,DES_DIS) VALUES (1,'JESUS MARIA')
INSERT INTO DISTRITO (ID_PRO,DES_DIS) VALUES (1,'LA MOLINA')
INSERT INTO DISTRITO (ID_PRO,DES_DIS) VALUES (1,'LA VICTORIA')
INSERT INTO DISTRITO (ID_PRO,DES_DIS) VALUES (1,'LIMA')
INSERT INTO DISTRITO (ID_PRO,DES_DIS) VALUES (1,'LINCE')
INSERT INTO DISTRITO (ID_PRO,DES_DIS) VALUES (1,'LOS OLIVOS')
INSERT INTO DISTRITO (ID_PRO,DES_DIS) VALUES (1,'LURIGANCHO')
INSERT INTO DISTRITO (ID_PRO,DES_DIS) VALUES (1,'LURIN')
INSERT INTO DISTRITO (ID_PRO,DES_DIS) VALUES (1,'MAGDALENA DEL MAR')
INSERT INTO DISTRITO (ID_PRO,DES_DIS) VALUES (1,'MIRAFLORES')
INSERT INTO DISTRITO (ID_PRO,DES_DIS) VALUES (1,'PACHACAMAC')
INSERT INTO DISTRITO (ID_PRO,DES_DIS) VALUES (1,'PUCUSANA')
INSERT INTO DISTRITO (ID_PRO,DES_DIS) VALUES (1,'PUEBLO LIBRE')
INSERT INTO DISTRITO (ID_PRO,DES_DIS) VALUES (1,'PUENTE PIEDRA')
INSERT INTO DISTRITO (ID_PRO,DES_DIS) VALUES (1,'PUNTA HERMOSA')
INSERT INTO DISTRITO (ID_PRO,DES_DIS) VALUES (1,'PUNTA NEGRA')
INSERT INTO DISTRITO (ID_PRO,DES_DIS) VALUES (1,'RIMAC')
INSERT INTO DISTRITO (ID_PRO,DES_DIS) VALUES (1,'SAN BARTOLO')
INSERT INTO DISTRITO (ID_PRO,DES_DIS) VALUES (1,'SAN BORJA')
INSERT INTO DISTRITO (ID_PRO,DES_DIS) VALUES (1,'SAN ISIDRO')
INSERT INTO DISTRITO (ID_PRO,DES_DIS) VALUES (1,'SAN JUAN DE LURIGANCHO')
INSERT INTO DISTRITO (ID_PRO,DES_DIS) VALUES (1,'SAN JUAN DE MIRAFLORES')
INSERT INTO DISTRITO (ID_PRO,DES_DIS) VALUES (1,'SAN LUIS')
INSERT INTO DISTRITO (ID_PRO,DES_DIS) VALUES (1,'SAN MARTIN DE PORRES')
INSERT INTO DISTRITO (ID_PRO,DES_DIS) VALUES (1,'SAN MIGUEL')
INSERT INTO DISTRITO (ID_PRO,DES_DIS) VALUES (1,'SANTA ANITA')
INSERT INTO DISTRITO (ID_PRO,DES_DIS) VALUES (1,'SANTA MARIA DEL MAR')
INSERT INTO DISTRITO (ID_PRO,DES_DIS) VALUES (1,'SANTA ROSA')
INSERT INTO DISTRITO (ID_PRO,DES_DIS) VALUES (1,'SANTIAGO DE SURCO')
INSERT INTO DISTRITO (ID_PRO,DES_DIS) VALUES (1,'SURQUILLO')
INSERT INTO DISTRITO (ID_PRO,DES_DIS) VALUES (1,'VILLA EL SALVADOR')
INSERT INTO DISTRITO (ID_PRO,DES_DIS) VALUES (1,'VILLA MARIA DEL TRIUNFO')
GO
INSERT INTO FORMA_USO (DES_FOR) VALUES ('Vía oral')
INSERT INTO FORMA_USO (DES_FOR) VALUES ('Vía sublingual')
INSERT INTO FORMA_USO (DES_FOR) VALUES ('Vía gastroentérica')
INSERT INTO FORMA_USO (DES_FOR) VALUES ('Vía rectal')
INSERT INTO FORMA_USO (DES_FOR) VALUES ('Vía parenteral')
INSERT INTO FORMA_USO (DES_FOR) VALUES ('Vía respiratoria')
INSERT INTO FORMA_USO (DES_FOR) VALUES ('Vía oftálmica')
INSERT INTO FORMA_USO (DES_FOR) VALUES ('Vía ótica')
INSERT INTO FORMA_USO (DES_FOR) VALUES ('Vía transdérmica')
GO
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('3M','3M Perú S.A.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('ABBOTT','Abbott Laboratorios S.A.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('ABBVIE','Abbvie S.A.S.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('ABL PHARMA','(Ver GRÜNENTHAL PERUANA S.A.)')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('AC FARMA','Lab. AC Farma S.A.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('ACCORD','Accord Healthcare S.A.C.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('ACHE','Ache')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('ADV. SCIENTIFIC','Advance Scientific del Perú')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('AFARMACH','Corporación Farmacéutica Afarmach S.A.C.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('AG FARMA SAC','Droguería AG Farma SAC')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('AJANTA PHARMA','Ajanta Pharma LTD.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('AKORN','(Ver MEDIFARMA S.A.)')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('ALBIS CONSUMO','Albis S.A.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('ALBIS NUTRICIA','Representante: Albis S.A.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('ALCON','Alcon Perú S.A.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('ALGOTEC','Lab. Algotec S.A.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('ALICORP','Alicorp')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('ALIFARMA','Alifarma Perú S.A.C.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('ALLERGAN','Lab. Allergan Internacional')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('ALPHARMACO SAC','(Ver Droguería LUDBER S.A.C.)')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('AMILPHARM','Amilpharm SAC')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('ANNEXA','(Ver Teva Perú S.A.)')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('APROPO','Apoyo a Programas de Población')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('ARENS','(D. CONTINENTAL S.A.)')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('ARION MASON','Corporación Arion S.A.C.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('ASG MEDICAL','ASG Inversiones EIRL')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('ASPEN','Aspen Perú S.A.(Representante de Wyeth Nutrition)')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('ASTELLAS','Astellas Pharma US INC.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('ASTRAZENECA','Lab. AstraZeneca Perú S.A.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('ATLANTIC COM.','Atlantic Comerce Trading S.A.C.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('ATLAS VISION','Atlas Vision (Ver FARMINDUSTRIA)')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('ATRAL-CIPAN','Grupo Atral-Cipan')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('AVENE','(Ver Euroderma Drogueria S.A.C.)')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('AVSA','Droguería Avsa Farmacéutica S.A.C.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('AXON PHARMA','Axon Pharma Perú S.A.C.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('B.BRAUN','B. Braun Medical Perú S.A.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('BACON','(Ver MALLINCKRODT)')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('BAGO','Lab. Bagó del Perú S.A.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('BAUSCH & LOMB','Lab. Bausch & Lomb')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('BAXLEY GROUP','Droguería Laboratorio Baxley Group S.A.C.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('BAXTER','Laboratorios Baxter del Perú S.A.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('BAYER','Bayer S.A.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('BAYER C.C.','Bayer Consumer Care (Ver BAYER S.A.)')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('BAYER S.P.','Bayer Schering Pharma (Ver BAYER S.A.)')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('BD','Lab. Becton Dickinson del Uruguay S.A. Suc. Perú')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('BEIERSDORF','Beiersdorf S.A.C.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('BIO REG PHARMA','Bio Reg Pharma S.A.C.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('BIOBASAL','Biobasal S.A., Basilea Suiza')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('BIOLIFE','(Ver PHARMA HOSTING)')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('BIOMEDICAL','Biomedical Sciences (Ver FARMINDUSTRIA)')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('BIOPAS','Laboratorios Biopas')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('BIOSANA','Droguería Laboratorios Biosana S.A.C.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('BIOSYNTEC','Biosyntec S.A.C.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('BIOTECH','Farmacéutica Biotech S.A.C.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('BIOTEFAR','Biotefar Perú SAC')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('BIOTOSCANA','Biotoscana Farma S.A.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('BMC FARMA','Brand And Marketing Consultores S.A.C.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('BMS','Bristol Myers Squibb S.A.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('BOEHRINGER','Laboratorio Boehringer Ingelheim')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('BRISAFARMA','Brisafarma S.A.C.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('CAFERMA','Caferma S.A.C.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('CALANIT','Calanit S.A.C.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('CARDIO PERFUS.','Cardio Perfusión EIRL')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('CARDIOPHARM','(ver FARMINDUSTRIA)')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('CASSARA','(Ver D&M PHARMA S.A.C.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('CATALYSIS','Laboratorios Catalysis S.L.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('CCV','Droguería Carlos Castañeda Veckarich')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('CECI FARMA','Ceci Farma Import S.R.L.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('CFARMA PERU','Droguería CFarma E.I.R.L.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('CHRISCAL CLEAN.','Chriscal Cleaning Products')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('CIFAR PERU','Corporación de Inversiones Farma Perú S.A.C.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('CINFA','(Ver QUIMICA SUIZA)')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('CIPA','Cipa')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('CIPLA','(Ver ESKE GROUP)')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('COFANA','(Ver TEVA PERU S.A)')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('COLGATE','Colgate Palmolive Perú S.A.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('COMIESA','Comiesa Druc S.A.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('CONTILAB','(Ver Distribuidora Continental 6 S.A.)')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('CORP. FARM.J&J','Corporación Farmacológica J&J')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('CORP.TRADE PLUS','Corporation Trade Plus del Perú S.A.C.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('CRESPAL','Laboratorios Crespal del Perú')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('D&M PHARMA','D&M Pharma Perú S.A.C.- Laboratorios Pablo Cassara')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('D.CONTINENTAL','Continental')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('D.CONTINENTAL 6','Distribuidora Continental 6 S.A.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('D.L.','Droguería Lafarpe S.A.C.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('DAJOS','Corporación Farmacéutica Dajos S.A.C.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('DANONE NUTRICIA','Danone Nutricia Early Life Nutrition')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('DANY','Distribuidora Dany S.R.L.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('DDLA','Distribuidora Droguería Las Américas S.A.C.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('DELFARMA','Laboratorios Delfarma S.A.C.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('DENTAID','Lab. Dentaid Perú S.A.C.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('DENTILAB','Dentilab del Perú')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('DEUTSCHE PHARMA','Lab. Deutsche Pharma S.A.C.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('DISPOLAB','Dispolab Farmacéutica Perú S.A.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('DR. ANDREU','Doctor Andreu Q.F. S.A.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('DR. ZAIDMAN','(Ver MEDIFARMA S.A.)')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('DRINTEFA','Droguería International Farma S.A.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('DROG. 2M & BR','Grupo 2M y BR S.A.C.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('DROG. FARBO','Droguería Farbo S.A.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('DROG. INFARVAL','Droguería Infarval E.I.R.L.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('DROG. LIPHARMA','Droguería Lipharma S.A.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('DROKASA','Drokasa Perú S.A.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('DRONNVELS','Dronnvels S.A.C.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('DROPESAC','Laboratorio Dropesac')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('DRUGS & BUSINES','Drugs & Business Perú S.A.C.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('DRUGTECH','(Ver FARMINDUSTRIA)')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('DUBONP','Laboratorio Dubonp S.A.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('DUPERU-INDUFAR','Droguerías Unidas del Perú S.A.C.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('E.B. PAREJA','E.B. Pareja Lecaros S.A. (Línea NUK)')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('ECHOPHARMA','Echopharma S.A.C.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('EFILA','Eficiencia Laboral S.A.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('ELI LILLY','Lab. Eli Lilly Interamerican Inc.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('ELIFARMA','Lab. Elifarma S.A.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('EMDIEX','Emdiex S.A. Emp. Multinacional de Imp. y Exp. S.A.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('EMS SIGMA PH.','EMS Sigma Pharma')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('ESKE GROUP','Eske Group')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('ESP.OFTALM.S.A.','Especialidades Oftalmológicas S.A. (Ver Ophtha)')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('EUROCHEM','European Chemicals (EUROCHEM) Div. Corp.Infarmasa')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('EUROCHEM-KIN','(Ver TEVA PERU S.A.)')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('EURODERMA','Euroderma Droguería S.A.C.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('EUROFARMA','Eurofarma Perú S.A.C.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('FADA PHARMA','Fada Pharma (Ver FARMINDUSTRIA)')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('FAES FARMA','Faes Farma')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('FAMILY DOCTOR','Family Doctor (Ver EFILA S.A.)')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('FAMYCARE','Laboratorio Famy Care S.A.C.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('FARBIOMEDIC','Corporación Farbiomedic S.A.C.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('FARMAC.DEL PERU','Laboratorios Farmacéutica del Perú S.A.C.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('FARMAC.LATINA','Farmacéutica Latina S.A.C.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('FARMACHIF','Laboratorios Farmachif')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('FARMACOM','Inversiones Farmacom S.A.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('FARMADUAL','Farmadual S.A.C.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('FARMAGE','Gedeon Richter Perú S.A.C.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('FARMAKONSUMA','Grupo Farmakonsuma S.A.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('FARMAQUIL','Lab. Farmaquil Perú S.A.C.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('FARMASUR','Laboratorios Farmasur S.A.C.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('FARMAVAL','Lab. Farmaval Perú S.A.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('FARMEDIC','Droguería Farmedic S.A.C.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('FARMINDUSTRIA','Farmindustria S.A. (Planta)')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('FARNATU','Lab. Farnatu E.I.R.L.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('FARPASA','(Ver MEDIFARMA S.A.)')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('FARVET','Droguería Laboratorio Farvet S.A.C.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('FERRER GRUPO','Lab. Ferrer Grupo Internacional S.A.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('FERRING','Ferring Pharmaceuticals (Ver QUIMICA SUIZA)')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('FLEET','Lab. C.B. Fleet Co. Inc.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('FRESENIUS KABI','Fresenius Kabi Perú')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('FREXEN','(Ver LABORATORIOS OFTALMICOS S.A.C)')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('G & R','Droguería G & R S.R.L.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('GABBLAN','LABORATORIOS GABBLAN S.A.C.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('GADOR','Gadorpharma S.A.C.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('GALDERMA','Lab. Galderma Perú')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('GALENICUM','Galenicum Health Perú SAC')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('GARDEN HOUSE','Lab. Garden House S.A.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('GEDEON RICHTER','Gedeon Richter')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('GENCOPHARMAC.','Laboratorio Gencopharmaceutical')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('GENFAR','Lab. Genfar Perú S.A.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('GENOMMA','Genomma Lab')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('GENZYME','Genzyme del Perú S.A.C.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('GIANFARMA','Lab. Gianfarma S.A.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('GLENMARK','Glenmark Pharmaceuticals Perú S.A.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('GLOBAL MEDFARMA','Global Med Farma')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('GLOBAL PHARMA','Droguería Global Pharma S.A.C.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('GP PHARM','GP Pharm S.A.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('GREY INVERS.','Grey Inversiones S.A.C.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('GRÜNENTHAL','Grünenthal Peruana S.A.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('GRUPO FAES','Grupo Faes S.A.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('GSK','GlaxoSmithKline Perú S.A.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('GYNOPHARM','(Ver FARMINDUSTRIA)')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('HANAI','Droguería Hanai SRL')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('HEEL','Biologische Heilmittel Heel Gmbh - Alemania')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('HERMES','Hermes Sweeteners LTD.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('HERSIL','Lab. Hersil S.A.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('HIMALAYA','(Ver Albis S.A.)')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('HOSPIRA','Hospira Perú S.R.L.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('INDUQUIMICA','Lab. Induquímica S.A. (Natural World)')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('INFERMED','Infermed S.A.C.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('INNOTECH','(Ver QUIMICA SUIZA)')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('INNOVADERM','Laboratorio Innovaderm (Representante ALBIS S.A.)')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('INTAS','(Ver ACCORD HEALTHCARE S.A.C.)')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('INTI','Laboratorio Inti Perú S.A.C.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('INTIPHARMA','Intipharma S.A.C.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('INTRALAB','Intradevco Industrial S.A. (Div. Farmac. Intralab)')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('IPCA','IPCA Laboratories Limited')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('IQFARMA','Instituto Quimioterápico S.A.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('ISDIN','Isdin Perú S.A.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('ISIS PHARMA','Isis Pharma')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('IST.GANASSINI','Istituto Ganassini S.P.A.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('ITA','Inversiones Ita SAC')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('IVAX','(Ver Teva Perú)')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('J & J SALUD','Corporación Farmacológica J & J Salud')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('J&J MEDICAL','Johnson & Johnson Medical')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('J&M ESPEC.FARM.','J&M Especialidades Farmacéuticas S.A.C.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('JANSSEN-CILAG','Janssen-Cilag')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('JOHNSON&JOHNSON','Johnson & Johnson del Perú')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('K2 PHARMAVIDA','(Ver FARMINDUSTRIA)')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('KEYFARM','Keyfarm S.A.C.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('KIMBERLY CLARK','Kimberly Clark del Perú')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('KNOP','(Ver Teva Perú.)')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('KOREPHARMA','(Ver DROPESAC)')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('LA COOPER','Laboratorios La Cooper')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('LA SANTE','La Santé')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('LAB.UNIDOS','Laboratorios Unidos S.A.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('LABEX CORP.','Labex Corporation S.A.C.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('LABOFAR','(Ver KEYFARM)')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('LABOMED','Labomed S.A.C.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('LABOT','Laboratorios Americanos - Labot S.A.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('LAFAGE','Laboratorio Lafage S.A.C.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('LAFAR PERU','Lafar Corporación Internacional S.A.C.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('LAFARMED','Laboratorio Farmacéutico Medical Perú S.A.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('LAFARPE','Lab. Farmacéutico Peruano S.R.L.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('LAFRANCOL','(Ver FARMINDUSTRIA)')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('LAMOSAN','Lamosan S.A.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('LANSIER','Lab. Lansier S.A.C.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('LCG','(Ver TEVA PERU S.A.)')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('LEMERY','Lab. Lemery, S.A. de C.V. (Ver WORLD PHARMA)')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('LEO PHARMA','(Ver QUIMICA SUIZA)')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('LKM PERU','LKM Perú S.A.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('LMB H.COLICHON','LMB H. Colichón S.A.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('LUDBER','Droguería Ludber S.A.C')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('LUKOLL','Lukoll S.A.C.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('LUNDBECK','Lundbeck Perú S.A.C.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('LUPIN','Laboratorio Lupin')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('LUSA','Laboratorios Unidos S.A.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('LUXOR PHARMAC.','Luxor Pharmaceutical S.A.C.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('M & G','Laboratorios M & G Vida Natural E.I.R.L.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('MACLEODS PHARM','Macleods Pharmaceuticals Limited Perú S.A.C.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('MAGMA','(Ver TEVA PERU S.A.)')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('MALLINCKRODT','Lab. Mallinckrodt')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('MAPERB DRUG','Maperb Drug S.A.C.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('MAQUIFARMA','Maquifarma E.I.R.L.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('MARFAN','(Ver TEVA PERU S.A.)')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('MARKOS','Lab. Farmacéuticos Markos S.A.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('MARVIC TRADING','Laboratorio Marvic Trading S.R.L.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('MASTER FARMA','Laboratorio Master Farma')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('MAVER','Maver Perú S.A.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('MC GLOBE','Mc Globe Incorporate S.A.C.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('MEAD JOHNSON','Mead Johnson Nutrition')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('MEDA PHARMA','Meda Pharma')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('MEDIDERM','(Ver FARMINDUSTRIA)')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('MEDIFARMA','Medifarma S.A.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('MEDIGROUP','Medigroup')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('MEDIHEALTH','(Ver ROEMMERS)')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('MEDINE PHARMA.','Medine Pharmaceuticals S.A.C.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('MEDPHAR','Medical Devices & Pharma S.A.C. - Medphar S.A.C.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('MEDROCK','Laboratorio Medrock')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('MEGA WE CARE','Mega Lifesciences PTY. PERU')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('MERCK','Merck Peruana S.A.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('MERZ','Merz Pharmaceuticals')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('MEXYL','(Ver QUIMICA SUIZA S.A.)')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('MI FARMA','Mi Farma')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('MKS UNIDOS','MKS Unidos S.A.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('MSD','Lab. Merck Sharp & Dohme Perú S.R.L.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('N Y S','N y S Compañia S.A.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('NATUMED','(Ver FARMINDUSTRIA)')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('NATURGEN','Laboratorios Naturales y Genéricos S.A.C.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('NESTLE','Nestlé Perú S.A.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('NEUMOBIOTICS','(Ver FARMINDUSTRIA)')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('NEUTROGENA','(Ver JOHNSON & JOHNSON)')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('NICOLICH','Lab. Nicolich S.A. (Ver FARMAVAL)')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('NINET','(Ver Química Suiza)')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('NIPRO','Nipro Medical Corporation Sucursal del Perú')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('NORDIC','Nordic Pharmaceutical Company S.A.C.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('NORGINE','Norgine Pharma')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('NORTHIA','Northia (Ver FARMINDUSTRIA)')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('NOVADERMA','Novaderma S.A.C.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('NOVARTIS C.H.','Novartis Biosciences Perú S.A. (Consumer Health)')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('NOVARTIS ONC','Novartis Div.Oncológica (Ver NOVARTIS PHARMA)')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('NOVARTIS OPHT.','Novartis Ophthalmics (Ver NOVARTIS PHARMA)')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('NOVARTIS PHARMA','Novartis Pharma Biosciences Perú S.A.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('NOVARTIS SANDOZ','Ver Novartis Biosciences Perú S.A.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('NOVARTIS TRANS.','Novartis Div. Transplante (Ver NOVARTIS PHARMA)')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('NOVARTIS-CIBA','Novartis Biosciences - Ciba Vision')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('NOVAX EIRL','Novax Eirl')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('NOVO NORDISK','Novo Nordisk Pharma Operations A/S Suc. del Perú')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('NPC','Nordic Pharmaceutical Company S.A.C.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('NYCOMED','Laboratorios Nycomed')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('OFTALMICOS','Laboratorios Oftálmicos S.A.C.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('OFTALMOMEDICA','Droguería Oftalmomédica S.A.C.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('OKASA','Okasa Pharma')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('OLI MED','Oli Med Perú S.A.C.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('OM PHARMA','OM Pharma S.A.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('OMDICA','Omdica S.A.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('ONCOMED','(Ver MEDIFARMA S.A.)')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('OPHTHA','Laboratorio Ophtha')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('OQ PHARMA','OQ Pharma S.A.C.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('ORBIS','Orbis International S.A.C.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('ORDESA','Lab. Ordesa')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('ORGANON','Organon International BV (Ver SCHERING PLOUGH)')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('OTARVASQ','Farmacéutica Otarvasq S.A.C.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('PAK FARMA','Droguería Pak Farma S.A.C.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('PALMAGYAR','Palmagyar S.A.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('PANALAB','(Ver ROEMMERS)')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('PERSONAL PROD.','Lab. Personal Products S.A.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('PERUFARMA','(Ver Distribuidores)')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('PERULAB','Perulab S.A.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('PERUMED','Representante: Albis S.A.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('PFIZER','Pfizer S.A.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('PFIZER CONSUMER','Pfizer Consumer Healthcare (Ver: Pfizer)')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('PHARBAL','Pharbal S.A.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('PHARMA HOSTING','Pharma Hosting Perú S.A.C.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('PHARMA PERU','Droguería F.J.F. Pharma Perú S.A.C.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('PHARMA ROY','Pharma Roy SAC')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('PHARMA-C','Laboratorio Pharma-C S.A.C.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('PHARMACEUTICAL','Pharmaceutical Distoloza SA')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('PHARMACHECK','Pharmacheck Perú S.A. Edificio Química Suiza')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('PHARMACOSMOS','Representante: Albis S.A.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('PHARMAGEN','Pharmagen S.A.C.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('PHARMALAB','(Ver Farmaindustria)')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('PHARMARIS','Pharmaris Perú S.A.C.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('PHARMATECH','Lab. Pharmatech')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('PHARMAVISION','Pharmavisión')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('PHARMED CORP.','Laboratorios Pharmed Corporation S.A.C.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('PHARMEX','Droguería Laboratorios Pharmex S.A.C.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('POEN','(Ver ROEMMERS)')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('PORTUGAL','Lab. Portugal S.R.L.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('PROCTER&GAMBLE','Procter & Gamble S.R.L.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('PROTELD','Laboratorios Proteld S.A.C.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('QUALICONT','(Ver Distribuidora Continental)')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('QUALIMAXX','Qualimax (Ver DIST. CONTINENTAL 6 S.A.)')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('QUALIPHARM','Qualipharm S.R.L.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('QUALIPHARM ORTH','Qualipharm Orthopedic')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('QUALITY PHARMA','Quality Pharma E.I.R.L.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('QUIARSA','Distribuidora Quiarsa S.A.C.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('QUILAB','Quilab')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('QUILAB FARMA','(Ver QUILAB)')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('QUILAB GENERIC.','(Ver QUILAB)')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('QUILAB OTC','(Ver QUILAB)')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('QUILLA PHARMA','Lab. Quilla Pharma S.A.C.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('QUIMFA','Quimfa Peru S.A.C.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('QUIMICA SUIZA','Química Suiza S.A.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('QUIROFANO','Laboratorio Quirofano')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('R&V FOOD GROUP','R&V Food Group S.A.C.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('RANBAXY-PRP','Ranbaxy-PRP Perú S.A.C.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('RECKITT BENCK.','Reckitt Benckiser')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('REFASA','Representaciones Farmacéuticas S.A.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('REIMED PHARMA','Reimed Pharma S.A.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('REMY','Instituto Bioquímico Dr. F. Remy S.A.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('REP. SEGURA','Representaciones Segura S.A.C.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('RHOVIC','Rhovic Pharmaceutical S.A.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('ROCA','Roca S.A.C.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('ROCHE','Productos Roche Q.F. S.A.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('RODMAD','Rodmad International')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('ROEL GRACE','Roel Grace S.A.C.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('ROEMMERS','Roemmers S.A.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('ROHA','Roha Arznelmittel Gmbh')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('ROKER','Laboratorio Roker Perú S.A.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('ROSTER','Roster S.A.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('ROWA','Lab. Rowa Pharmaceuticals')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('ROWE','(Ver ROEMMERS)')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('ROWEFEM','(Ver ROEMMERS)')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('RYMCO','Rymco (Ver DIST. CONTINENTAL 6 S.A.)')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('S.J.ROXFARMA','Lab. Farmacéutico San Joaquin Roxfarma S.A.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('SANCELA','Sancela')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('SANDERSON','Sanderson S.A. (PERU)')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('SANDOZ','(Ver ROEMMERS)')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('SANITAS','(Ver TEVA PERU S.A.)')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('SANKYO','(Ver QUIMICA SUIZA)')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('SANOFI AVENTIS','Grupo Sanofi Aventis')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('SANOFI PASTEUR','Sanofi Pasteur')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('SAVAL','Laboratorios Saval ( Ver FARMAVAL)')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('SCALUP','Scalup Importaciones S.A.C.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('SCHERING PLOUGH','(Ver MSD)')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('SENOSIAIN','Laboratorios Senosiain')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('SERVIER','(Ver Biopas)')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('SEVEN PHARMA','Seven Pharma S.A.C.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('SHERFARMA','Lab. Sherfarma S.A.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('SIEGFRIED','Labotarorios Siegfried S.A.C.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('SIT DESMA','SIT Desma Health Care N.V.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('SKIN MASTER','Skin Master Perú SAC')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('SOLCO','Distribuidor: Albis S.A.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('SOLTON','Solton Pharma S.A.C.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('SOLUTIONS M.I.','Solutions Medical Import SAC')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('SOLVAY','(Ver QUIMICA SUIZA)')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('SOPHIA','(Ver LABORATORIOS OFTALMICOS S.A.C.)')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('STIEFEL','(Ver GSK)')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('SUN PHARMA','Sun Pharmaceutical')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('SUNDOWN','Lab. Sundown')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('SUNSHINE','(Ver QUIARSA S.A.C.)')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('TABLETS','Tablets (India) LTD.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('TAKEDA','Takeda SRL')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('TECHSPHERE','Techsphere Perú S.A.C.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('TECNOFARMA','Tecnofarma S.A.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('TEMIS LOSTALO','Temis Lostaló')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('TEOFARMA','Teofarma Perú S.A.C.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('TERBOL','Lab. Terbol Perú S.A.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('TERBONOVA','(Ver TERBOL)')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('TEVA','TEVA PERU S.A.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('TEVA THERAMEX','(Ver TEVA PERU S.A.)')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('TORRES PHARMA','Torres Pharma S.A.C.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('TRIFARMA','(Ver MEDIFARMA S.A.)')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('UNIFARM','Lab. Unión Farmacéutica Nacional S.R.L.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('UNIMED','Unimed del Perú S.A.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('UNIPHARM','Unipharm S.A.C.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('URIAGE','Laboratoires Dermatologiques Uriage')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('VALEANT PERU','Valeant Farmacéutica Perú SRL')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('VANOCI','VANOCI E.I.R.L.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('VENDIBAND','Vendiband (Ver DIST. CONTINENTAL 6 S.A.)')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('VIDASOL','Vidasol E.I.R.L.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('VIFARMA','Droguería Vifarma E.I.R.L.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('VIFOR','Vifor')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('VITABIOTICS','Vitabiotics')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('VITALIS','Vitalis Perú S.A.C.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('VYSER','(Ver ESKE GROUP)')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('WELFARK','Lab. Welfark Perú S.A.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('WELFARK-IESA','(Ver Lab. WELFARK PERU S.A.)')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('WILFAR','Droguería Wilfar SAC')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('WOCKHARDT','Wockhardt Limited')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('WORLD PHARMA','World Pharma S.A.C.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('WÖRWAG PHARMA','Representante: Albis S.A.')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('WYETH NUTRICION','(Ver ASPEN PERU S.A.)')
INSERT INTO LABORATORIO (NOM_LAB,RSO_LAB) VALUES ('YOBEL','Yobel Supply Chain Management S.A.')
GO
INSERT INTO FARMACIA (ID_DIS,NOM_FAR,DIR_FAR,CORX_FAR,CORDY_FAR) VALUES (30,'Boticas Fasa','Av. Aviación 2499, San Borja 15037, Perú',-12.090992,-77.002926)
INSERT INTO FARMACIA (ID_DIS,NOM_FAR,DIR_FAR,CORX_FAR,CORDY_FAR) VALUES (35,'Inka Farma','Av. Universitaria 691, San Martín de Porres 15107, Perú',-12.019792,-77.076218)
INSERT INTO FARMACIA (ID_DIS,NOM_FAR,DIR_FAR,CORX_FAR,CORDY_FAR) VALUES (15,'Farmacia Universal','Emancipación 799, Distrito de Lima 15001, Perú',-12.044732,-77.040272)
INSERT INTO FARMACIA (ID_DIS,NOM_FAR,DIR_FAR,CORX_FAR,CORDY_FAR) VALUES (32,'BOTICAS Biofarma','Av Gran Chimú 641, San Juan de Lurigancho 15401, Perú',-12.026101,-77.003152)
INSERT INTO FARMACIA (ID_DIS,NOM_FAR,DIR_FAR,CORX_FAR,CORDY_FAR) VALUES (7,'Inkafarma','Alameda Los Cedros, Chorrillos 15067, Perú',-12.203856,-77.014036)
INSERT INTO FARMACIA (ID_DIS,NOM_FAR,DIR_FAR,CORX_FAR,CORDY_FAR) VALUES (15,'Boticas Arcángel Centro Comercial Minka','Av. Argentina 3093, Lima 07001, Perú',-12.047365,-77.11154)
INSERT INTO FARMACIA (ID_DIS,NOM_FAR,DIR_FAR,CORX_FAR,CORDY_FAR) VALUES (30,'Boticas Arcángel','Remintony 220, San Borja 15036, Perú',-12.099047,-77.011005)
INSERT INTO FARMACIA (ID_DIS,NOM_FAR,DIR_FAR,CORX_FAR,CORDY_FAR) VALUES (41,'Boticas Arcangel','Los Negocios, 187, Esquina, Calle Los Negocios 187, Surquillo 15047, Perú',-12.105421,-77.021973)
INSERT INTO FARMACIA (ID_DIS,NOM_FAR,DIR_FAR,CORX_FAR,CORDY_FAR) VALUES (36,'Boticas Arcángel','Padre Urraca 2605, San Miguel 15087, Perú',-12.078176,-77.0913)
INSERT INTO FARMACIA (ID_DIS,NOM_FAR,DIR_FAR,CORX_FAR,CORDY_FAR) VALUES (32,'Botica Inkafarma','Los Jardines Oeste, San Juan de Lurigancho 15431, Perú',-12.00386, -77.002531)
INSERT INTO FARMACIA (ID_DIS,NOM_FAR,DIR_FAR,CORX_FAR,CORDY_FAR) VALUES (17,'Bótica Inkafarma','Av. Universitaria 1904, Los Olivos 15302, Perú',-12.006362,-77.082091)
INSERT INTO FARMACIA (ID_DIS,NOM_FAR,DIR_FAR,CORX_FAR,CORDY_FAR) VALUES (40,'Boticas BTL','Avenida Alfredo Benavides Diez Canseco, Santiago de Surco 15039, Perú',-12.128359,-76.992444)
INSERT INTO FARMACIA (ID_DIS,NOM_FAR,DIR_FAR,CORX_FAR,CORDY_FAR) VALUES (15,'Botica Fasa','Cusco 397, Distrito de Lima 15001, Perú',-12.050628,-77.030378)
INSERT INTO FARMACIA (ID_DIS,NOM_FAR,DIR_FAR,CORX_FAR,CORDY_FAR) VALUES (15,'BOTICAS PERÚ','Colmena 798, Distrito de Lima 15001, Perú',-12.050814,-77.036264)
INSERT INTO FARMACIA (ID_DIS,NOM_FAR,DIR_FAR,CORX_FAR,CORDY_FAR) VALUES (41,'G y M Bóticas','Av. Aviación 4036, Surquillo 15038, Perú',-12.117055,-76.999083)
INSERT INTO FARMACIA (ID_DIS,NOM_FAR,DIR_FAR,CORX_FAR,CORDY_FAR) VALUES (9,'Boticas Fasa','Victor A Belaunde 300, Comas 15312, Perú',-11.93904,-77.051761)
INSERT INTO FARMACIA (ID_DIS,NOM_FAR,DIR_FAR,CORX_FAR,CORDY_FAR) VALUES (30,'MiFarma','Av San Luis 2022, San Borja 15037, Perú',-12.090534,-76.996313)
INSERT INTO FARMACIA (ID_DIS,NOM_FAR,DIR_FAR,CORX_FAR,CORDY_FAR) VALUES (36,'Bótica Inkafarma','Calle Elmer Faucett 395, San Miguel 15088, Perú',-12.066293,-77.097506)
INSERT INTO FARMACIA (ID_DIS,NOM_FAR,DIR_FAR,CORX_FAR,CORDY_FAR) VALUES (11,'MiFarma','Av. Alisos 120, Independencia 15311, Perú',-12.080174,-77.02279)
INSERT INTO FARMACIA (ID_DIS,NOM_FAR,DIR_FAR,CORX_FAR,CORDY_FAR) VALUES (13,'Boticas BTL','Av. Los Constructores, La Molina 15012, Perú',-12.062534,-76.945583)
GO
update FARMACIA
set GEO_LUGAR = geography::STPointFromText('POINT(' + CAST(CORX_FAR AS
VARCHAR(20)) + ' '+CAST(CORDY_FAR AS VARCHAR(20)) + ')', 4326)
GO






