//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI_Farma.pe.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BD_FARMACIAEntities : DbContext
    {
        public BD_FARMACIAEntities()
            : base("name=BD_FARMACIAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADVERTENCIA> ADVERTENCIAs { get; set; }
        public virtual DbSet<DEPARTAMENTO> DEPARTAMENTOes { get; set; }
        public virtual DbSet<DISTRITO> DISTRITOes { get; set; }
        public virtual DbSet<FARMACIA> FARMACIAs { get; set; }
        public virtual DbSet<FAVORITO> FAVORITOes { get; set; }
        public virtual DbSet<FORMA_USO> FORMA_USO { get; set; }
        public virtual DbSet<LABORATORIO> LABORATORIOs { get; set; }
        public virtual DbSet<LABORATORIO_MEDICAMENTO> LABORATORIO_MEDICAMENTO { get; set; }
        public virtual DbSet<MEDICAMENTO> MEDICAMENTOes { get; set; }
        public virtual DbSet<MEDICAMENTO_FARMACIA> MEDICAMENTO_FARMACIA { get; set; }
        public virtual DbSet<MEDICAMENTO_SINTOMA> MEDICAMENTO_SINTOMA { get; set; }
        public virtual DbSet<PERSONA> PERSONAs { get; set; }
        public virtual DbSet<PROMOCION> PROMOCIONs { get; set; }
        public virtual DbSet<PROVINCIA> PROVINCIAs { get; set; }
        public virtual DbSet<SINTOMA> SINTOMAs { get; set; }
        public virtual DbSet<USUARIO> USUARIOs { get; set; }
    
        public virtual ObjectResult<USP_FARMACIAS_X_DISTRITO_Result> USP_FARMACIAS_X_DISTRITO(Nullable<int> iD_DIS)
        {
            var iD_DISParameter = iD_DIS.HasValue ?
                new ObjectParameter("ID_DIS", iD_DIS) :
                new ObjectParameter("ID_DIS", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_FARMACIAS_X_DISTRITO_Result>("USP_FARMACIAS_X_DISTRITO", iD_DISParameter);
        }
    }
}
