//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI_Farma.pe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONA
    {
        public int PER_ID { get; set; }
        public int ID_USU { get; set; }
        public string NOM_PER { get; set; }
        public string APEP_PER { get; set; }
        public string APEM_PER { get; set; }
        public Nullable<System.DateTime> FNAC_PER { get; set; }
    
        public virtual USUARIO USUARIO { get; set; }
    }
}
