//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI_Farma.pe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROMOCION
    {
        public int ID_PRO { get; set; }
        public int ID_MED { get; set; }
        public int ID_FAR { get; set; }
        public string DES_PRO { get; set; }
    
        public virtual FARMACIA FARMACIA { get; set; }
        public virtual MEDICAMENTO MEDICAMENTO { get; set; }
    }
}
